# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20160908_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('Application', 'Applied'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired'), ('Removed', 'Removed')], default='Applied', max_length=64),
        ),
    ]
