# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_role_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Recruiting', 'Recruiting'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed'), ('Aborted', 'Aborted')], default='Planning', max_length=64),
        ),
    ]
