# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20160912_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, to='challenge.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsoring_organizations',
            field=models.ManyToManyField(blank=True, to='challenge.Organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='challenge.Tag'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='challenge.Tag'),
        ),
    ]
