# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20160913_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Designer', 'Designer'), ('Developer', 'Developer'), ('Analyst', 'Analyst'), ('Communications', 'Communications'), ('Project Lead', 'Project Lead'), ('Champion', 'Champion'), ('Project Support', 'Project Support'), ('Project Strategy', 'Project Strategy')], default='Vacant', max_length=64),
        ),
    ]
