# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20160913_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(default='images/organization_images/nothing.jpg', upload_to='images/organization_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='images/project_images/nothing.jpg', upload_to='images/project_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, default='images/tag_images/nothing.jpg', null=True, upload_to='images/tag_images/%Y/%m/%d/%H_%M_%S'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='images/team_images/nothing.jpg', upload_to='images/team_images/%Y/%m/%d/%H_%M_%S'),
        ),
    ]
