# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0010_auto_20160914_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Resolved', 'Resolved'), ('Improving', 'Improving'), ('Worsening', 'Worsening')], default='Active', max_length=64)),
                ('scope', models.CharField(choices=[('Community', 'Community'), ('Municipal', 'Municipal'), ('Regional', 'Regional'), ('Provincial/State', 'Provincial/State'), ('National', 'National'), ('International', 'International')], default='Municipal', max_length=64)),
                ('current_state', models.TextField(blank=True, null=True)),
                ('ideal_state', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('image', models.ImageField(default='images/issue_images/nothing.jpg', upload_to='images/issue_images/%Y/%m/%d/%H_%M_%S')),
                ('priority', models.IntegerField(default=1)),
                ('rating', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('geo_x', models.FloatField(blank=True, null=True)),
                ('geo_y', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='issue_followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(max_length=255)),
                ('start_date', models.DateField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('impact_statement', models.TextField(max_length=1000)),
                ('priority', models.IntegerField(default=1)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('image', models.ImageField(default='images/story_images/nothing.jpg', upload_to='images/story_images/%Y/%m/%d/%H_%M_%S')),
                ('geo_x', models.FloatField(blank=True, null=True)),
                ('geo_y', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='story_followers', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='challenge.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Project')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='stories',
            field=models.ManyToManyField(to='challenge.Story'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, to='challenge.Tag'),
        ),
    ]
