# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_auto_20160915_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='slug',
        ),
        migrations.AddField(
            model_name='story',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
