# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_auto_20160807_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.Organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsoring_organizations',
            field=models.ManyToManyField(to='challenge.Organization'),
        ),
    ]
