# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_auto_20160916_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='zoom',
            field=models.IntegerField(default=6, help_text='Sets the default zoom'),
        ),
        migrations.AddField(
            model_name='member',
            name='zoom',
            field=models.IntegerField(default=6, help_text='Sets the default zoom'),
        ),
        migrations.AddField(
            model_name='project',
            name='zoom',
            field=models.IntegerField(default=6, help_text='Sets the default zoom'),
        ),
        migrations.AddField(
            model_name='story',
            name='zoom',
            field=models.IntegerField(default=6, help_text='Sets the default zoom'),
        ),
        migrations.AddField(
            model_name='team',
            name='zoom',
            field=models.IntegerField(default=6, help_text='Sets the default zoom'),
        ),
    ]
