# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_auto_20160916_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='geo_x',
            field=models.FloatField(blank=True, default=54.16045, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='geo_y',
            field=models.FloatField(blank=True, default=-92.01873, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='zoom',
            field=models.IntegerField(blank=True, default=6, help_text='Sets the default zoom', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='geo_x',
            field=models.FloatField(blank=True, default=54.16045, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='geo_y',
            field=models.FloatField(blank=True, default=-92.01873, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='zoom',
            field=models.IntegerField(blank=True, default=6, help_text='Sets the default zoom', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='geo_x',
            field=models.FloatField(blank=True, default=54.16045, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='geo_y',
            field=models.FloatField(blank=True, default=-92.01873, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='zoom',
            field=models.IntegerField(blank=True, default=6, help_text='Sets the default zoom', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='geo_x',
            field=models.FloatField(blank=True, default=54.16045, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='geo_y',
            field=models.FloatField(blank=True, default=-92.01873, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='zoom',
            field=models.IntegerField(blank=True, default=6, help_text='Sets the default zoom', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='geo_x',
            field=models.FloatField(blank=True, default=54.16045, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='geo_y',
            field=models.FloatField(blank=True, default=-92.01873, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='zoom',
            field=models.IntegerField(blank=True, default=6, help_text='Sets the default zoom', null=True),
        ),
    ]
