# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0017_auto_20160916_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='stories',
        ),
        migrations.AddField(
            model_name='story',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.Issue'),
            preserve_default=False,
        ),
    ]
